print("--- Gerenciamento de Jogadores e Times ---")
print()
print("Escolha uma opção:")
print("1 - Listar times")
print("2 - Adicionar um time")
print("3 - Excluir um time")
print("4 - Adicionar jogador a um time")
print("5 - Excluir jogador de um time")
print("6 - Listar jogadores de um time")